---
name: Artemis-Config
version: 2.010002
author:
  - 'OSRC SysInt Team <osrc-sysint@elbe.amd.com>'
abstract: Artemis configuration module!
license: restrictive
requires:
  Hash::Merge::Simple: 0
  perl: 5.010
build_requires:
  Test::More: 0
provides:
  Artemis::Config:
    file: lib/Artemis/Config.pm
    version: 2.010002
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
